// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUL4Wv7TPLgBuOGFxsKORyqSYKJ5M8NSs',
    appId: '1:109154772269:android:67d1bb9238be31d91c1fa4',
    messagingSenderId: '109154772269',
    projectId: 'logn-d506f',
    storageBucket: 'logn-d506f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8XdKshhrcoEpXZO0G6E-ognazNmmq3k',
    appId: '1:109154772269:ios:2d0a47fbc7e2a8c51c1fa4',
    messagingSenderId: '109154772269',
    projectId: 'logn-d506f',
    storageBucket: 'logn-d506f.appspot.com',
    iosClientId: '109154772269-nmh9rr2nvt083p0n5kjubglqiku5jtn0.apps.googleusercontent.com',
    iosBundleId: 'com.eraa.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8XdKshhrcoEpXZO0G6E-ognazNmmq3k',
    appId: '1:109154772269:ios:2d0a47fbc7e2a8c51c1fa4',
    messagingSenderId: '109154772269',
    projectId: 'logn-d506f',
    storageBucket: 'logn-d506f.appspot.com',
    iosClientId: '109154772269-nmh9rr2nvt083p0n5kjubglqiku5jtn0.apps.googleusercontent.com',
    iosBundleId: 'com.eraa.exam',
  );
}
